#ifndef display_
#define display_
void display(void);
void Floor1redraw(void);
void Floor2redraw(void);
void Floor3redraw(void);
void Display(void);
void drawFireZone1(void);
void drawFireZone2(void);
void drawFireZone3(void);
void drawFireZone4(void);
void drawFireZone5(void);
void drawFireZone6(void);
void drawFireZone7(void);
void drawFireZone8(void);
void drawSecZone1(void);
void drawSecZone2(void);
void drawSecZone3(void);
void drawSecZone4(void);
void drawSecZone5(void);
void drawSecZone6(void);
void drawSecZone7(void);
void drawSecZone8(void);
void Display1(void);
#endif